apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracegen
  annotations:
    "sidecar.jaegertracing.io/inject": "simple-prod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracegen
  template:
    metadata:
      labels:
        app: tracegen
    spec:
      containers:
      - name: tracegen
        image: jaegertracing/jaeger-tracegen:1.17
        args:
        - -duration=30m
        - -workers=1
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.18
        args:
        - --reporter.grpc.host-port=dns:///simplest-collector-headless.prometheus.svc.cluster.local:14250
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 6831
          name: jg-compact-trft
          protocol: UDP    