apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka-cluster
  labels:
    app: strimzi
spec:
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  selector:
    app.kubernetes.io/name: kafka-exporter
  type: NodePort
  